nama = input("nama kamu siapa :")
asal = input("dari mana kamu :")
sekolah = input("sebelumnya kamu sekolah dimana ?")
print ("selamat siang"+nama )
print ("wah dari "+asal)
print("pasti menyenangkan sekolah di"+sekolah)
